junit_tests(
    name = 'runner',
    dependencies = [
        '3rdparty/intellij:sdk',
        '3rdparty/intellij:python-plugin',
        '3rdparty/intellij:scala-plugin',
        'src:pants-intellij-plugin-scala',
        'testFramework:test-lib'
    ],
    sources = globs('*.java')
)