# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
  sources = globs('*.java'),
  dependencies=[
    '3rdparty/jvm/com/google/auto/value',
  ]
)
