# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: true
  branches:
    include:
      - "*"

jobs:
  - job: test_job
    timeoutInMinutes: 90

    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        jdk8:
          jdk_version: "1.8"

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: |
        ./scripts/setup-ci-environment.sh && ./scripts/run-tests-ci.sh
      displayName: 'Run test'
