# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: true
  branches:
    include:
      - "*"

jobs:
  - job: test_job
    timeoutInMinutes: 90

    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        shard0:
          jdk_version: "1.8"
          IJ_ULTIMATE: false
          PANTS_TEST_JUNIT_TEST_SHARD: 0/2
        shard1:
          jdk_version: "1.8"
          IJ_ULTIMATE: false
          PANTS_TEST_JUNIT_TEST_SHARD: 1/2

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: |
        ./scripts/setup-ci-environment.sh && ./scripts/run-tests-ci.sh
      displayName: 'Run test'
