# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - "*"

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    jdk8:
      jdk_version: "1.8"
      # Use Python version
      # Use the specified version of Python from the tool cache, optionally adding it to the PATH
      - task: UsePythonVersion@0
        inputs:
        versionSpec: '3.7'
        addToPath: true

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ./scripts/setup-ci-environment.sh
    ./scripts/run-tests-ci.sh
  displayName: 'Run a multi-line script'
