#!/usr/bin/env bash

source build-support/python/libvirtualenv.sh

PIP_OPTIONS=(
  --allow-external pantsbuild.pants
  --allow-unverified pantsbuild.pants
)

setup_virtualenv pants pantsbuild.pants==0.0.32 '--allow-external elementtree --allow-unverified elementtree'

exec pants "$@"
