# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='simple',
  source='HelloWorld.scala',
  main='org.pantsbuild.testproject.failures.simple.HelloWorld',
)
