junit_tests(name='java',
  sources=rglobs('*.java'),
  dependencies=[
    '3rdparty:junit',
    'intellij-integration/extras/src/main/java/org/pantsbuild/testproject:lib',
  ],
)

resources(
  name='resources',
  sources=rglobs('*'),
)
