scala_library(name='missingdepswhitelist',
  sources=globs('*.scala'),
  dependencies=[
    'testprojects/src/java/org/pantsbuild/testproject/publish/hello/greet',
    'intellij-integration/src/scala/org/pantsbuild/testproject/missingdepswhitelist2'
  ]
)