scala_library(name='missingdepswhitelist',
  sources=globs('*.scala'),
  dependencies=[
    'testprojects/src/java/com/pants/testproject/publish/hello/greet',
    'intellij-integration/src/scala/com/pants/testproject/missingdepswhitelist2'
  ]
)