java_library(
    name = 'test-lib',
    dependencies = [
        '3rdparty/intellij:sdk',
        '3rdparty/intellij:python-plugin',
        '3rdparty/intellij:scala-plugin',
        'src:pants-intellij-plugin-scala'
    ],
    sources = globs('*.java')
)