name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'ide-probe/**'
  pull_request:
    paths:
      - 'ide-probe/**'

jobs:
  test_probe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build image
      run: docker build --tag testimage .
    - name: test
      run: docker run testimage sh ci/test-probe
  test_pants_extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker build --tag testimage .
      - name: test
        run: docker run testimage sh ci/test-pants
  test_scala_extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker build --tag testimage .
      - name: test
        run: docker run testimage sh ci/test-scala